"""AI Search Intelligence Models

Revision ID: 61c8d5f1d5d3
Revises: 
Create Date: 2026-07-14 13:22:32.885492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61c8d5f1d5d3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('is_client', sa.Boolean(), nullable=False),
    sa.Column('is_competitor', sa.Boolean(), nullable=False),
    sa.Column('is_partner', sa.Boolean(), nullable=False),
    sa.Column('mention_count', sa.Integer(), nullable=False),
    sa.Column('citation_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_table('prompts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('intent', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.String(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('providers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('trend_data',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('dimension', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historical_scores',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('analysis_id', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('ai_readiness_score', sa.Float(), nullable=False),
    sa.Column('visibility', sa.Float(), nullable=False),
    sa.Column('mentions', sa.Integer(), nullable=False),
    sa.Column('citations', sa.Integer(), nullable=False),
    sa.Column('entity_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompt_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('prompt_id', sa.String(), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('full_response', sa.Text(), nullable=True),
    sa.Column('latency', sa.Float(), nullable=False),
    sa.Column('token_usage', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provider_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('latency', sa.Float(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('token_usage', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visibility_metrics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('ai_visibility_percent', sa.Float(), nullable=False),
    sa.Column('citation_percent', sa.Float(), nullable=False),
    sa.Column('mention_percent', sa.Float(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=False),
    sa.Column('loss_rate', sa.Float(), nullable=False),
    sa.Column('avg_citation_position', sa.Float(), nullable=False),
    sa.Column('avg_response_position', sa.Float(), nullable=False),
    sa.Column('prompt_coverage', sa.Float(), nullable=False),
    sa.Column('competitor_coverage', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('citations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('prompt_run_id', sa.String(), nullable=False),
    sa.Column('citation_title', sa.String(), nullable=True),
    sa.Column('citation_url', sa.Text(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('root_domain', sa.String(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('anchor_text', sa.Text(), nullable=True),
    sa.Column('response_snippet', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('citation_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['prompt_run_id'], ['prompt_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entity_analysis',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('prompt_run_id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_name', sa.String(), nullable=False),
    sa.Column('coverage_status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['prompt_run_id'], ['prompt_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entity_analysis')
    op.drop_table('citations')
    op.drop_table('visibility_metrics')
    op.drop_table('provider_logs')
    op.drop_table('prompt_runs')
    op.drop_table('historical_scores')
    op.drop_table('trend_data')
    op.drop_table('providers')
    op.drop_table('prompts')
    op.drop_table('brands')
    # ### end Alembic commands ###
