"""AI Engine V2 Updates

Revision ID: 74d5482cffa6
Revises: ccbaebd22c2d
Create Date: 2026-07-14 15:56:24.121262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74d5482cffa6'
down_revision: Union[str, None] = 'ccbaebd22c2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_aliases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('brand_id', sa.String(), nullable=False),
    sa.Column('alias_name', sa.String(), nullable=False),
    sa.Column('alias_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competitor_mentions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('prompt_run_id', sa.String(), nullable=False),
    sa.Column('competitor_name', sa.String(), nullable=False),
    sa.Column('times_cited', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['prompt_run_id'], ['prompt_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('prompt_runs', sa.Column('prompt_category', sa.String(), nullable=True))
    op.add_column('prompt_runs', sa.Column('relevance_score', sa.Float(), nullable=False))
    op.add_column('prompt_runs', sa.Column('valid_response', sa.Boolean(), nullable=False))
    op.add_column('prompt_runs', sa.Column('validation_reason', sa.Text(), nullable=True))
    op.add_column('prompt_runs', sa.Column('sentiment', sa.String(), nullable=True))
    op.add_column('prompt_runs', sa.Column('brand_mentions_count', sa.Integer(), nullable=False))
    op.add_column('prompt_runs', sa.Column('product_mentions_count', sa.Integer(), nullable=False))
    op.add_column('prompt_runs', sa.Column('competitor_mentions_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prompt_runs', 'competitor_mentions_count')
    op.drop_column('prompt_runs', 'product_mentions_count')
    op.drop_column('prompt_runs', 'brand_mentions_count')
    op.drop_column('prompt_runs', 'sentiment')
    op.drop_column('prompt_runs', 'validation_reason')
    op.drop_column('prompt_runs', 'valid_response')
    op.drop_column('prompt_runs', 'relevance_score')
    op.drop_column('prompt_runs', 'prompt_category')
    op.drop_table('competitor_mentions')
    op.drop_table('brand_aliases')
    # ### end Alembic commands ###
