"""Add remediation_note

Revision ID: ccbaebd22c2d
Revises: 61c8d5f1d5d3
Create Date: 2026-07-14 14:28:14.425720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccbaebd22c2d'
down_revision: Union[str, None] = '61c8d5f1d5d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompt_runs', sa.Column('remediation_note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prompt_runs', 'remediation_note')
    # ### end Alembic commands ###
